name: 'ae_sandbox_apd_vbhagnani'  # ✅ Valid (lowercase + underscore)
  # ✅ Ensure this matches your actual project name
version: '1.0.0'
config-version: 2


models:
  ae_sandbox_apd_vbhagnani:
    bronze:
      +materialized: table
