name: 'ae_sandbox_apd_vbhagnani'  # ✅ Valid (lowercase + underscore)
version: '1.0.0'
config-version: 2

models:
  ae_sandbox_apd_vbhagnani:
    +materialized: table

  # Configure raw models (models inside the raw folder)
  ae_sandbox_apd_vbhagnani.raw:
    +materialized: table  # Ensure raw models are materialized as tables (or adjust as needed)
